/*
 * Rainbow-API
 * The responses of the open api in swagger focus on the data field rather than the code and the message fields
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.client.model.GormDeletedAt;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ModelsContract
 */
public class ModelsContractTest {
    private final ModelsContract model = new ModelsContract();

    /**
     * Model tests for ModelsContract
     */
    @Test
    public void testModelsContract() {
        // TODO: test ModelsContract
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'appId'
     */
    @Test
    public void appIdTest() {
        // TODO: test appId
    }

    /**
     * Test the property 'baseUri'
     */
    @Test
    public void baseUriTest() {
        // TODO: test baseUri
    }

    /**
     * Test the property 'chainId'
     */
    @Test
    public void chainIdTest() {
        // TODO: test chainId
    }

    /**
     * Test the property 'chainType'
     */
    @Test
    public void chainTypeTest() {
        // TODO: test chainType
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'deletedAt'
     */
    @Test
    public void deletedAtTest() {
        // TODO: test deletedAt
    }

    /**
     * Test the property 'hash'
     */
    @Test
    public void hashTest() {
        // TODO: test hash
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'ownerAddress'
     */
    @Test
    public void ownerAddressTest() {
        // TODO: test ownerAddress
    }

    /**
     * Test the property 'royaltiesAddress'
     */
    @Test
    public void royaltiesAddressTest() {
        // TODO: test royaltiesAddress
    }

    /**
     * Test the property 'royaltiesBps'
     */
    @Test
    public void royaltiesBpsTest() {
        // TODO: test royaltiesBps
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'symbol'
     */
    @Test
    public void symbolTest() {
        // TODO: test symbol
    }

    /**
     * Test the property 'tokensBurnable'
     */
    @Test
    public void tokensBurnableTest() {
        // TODO: test tokensBurnable
    }

    /**
     * Test the property 'tokensTransferableByAdmin'
     */
    @Test
    public void tokensTransferableByAdminTest() {
        // TODO: test tokensTransferableByAdmin
    }

    /**
     * Test the property 'tokensTransferableByUser'
     */
    @Test
    public void tokensTransferableByUserTest() {
        // TODO: test tokensTransferableByUser
    }

    /**
     * Test the property 'transferCooldownTime'
     */
    @Test
    public void transferCooldownTimeTest() {
        // TODO: test transferCooldownTime
    }

    /**
     * Test the property 'txId'
     */
    @Test
    public void txIdTest() {
        // TODO: test txId
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

}
