/*
 * Rainbow-API
 * The responses of the open api in swagger focus on the data field rather than the code and the message fields
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.client.model.GormDeletedAt;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ModelsExposedFile
 */
public class ModelsExposedFileTest {
    private final ModelsExposedFile model = new ModelsExposedFile();

    /**
     * Model tests for ModelsExposedFile
     */
    @Test
    public void testModelsExposedFile() {
        // TODO: test ModelsExposedFile
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'deletedAt'
     */
    @Test
    public void deletedAtTest() {
        // TODO: test deletedAt
    }

    /**
     * Test the property 'fileName'
     */
    @Test
    public void fileNameTest() {
        // TODO: test fileName
    }

    /**
     * Test the property 'fileSize'
     */
    @Test
    public void fileSizeTest() {
        // TODO: test fileSize
    }

    /**
     * Test the property 'fileType'
     */
    @Test
    public void fileTypeTest() {
        // TODO: test fileType
    }

    /**
     * Test the property 'fileUrl'
     */
    @Test
    public void fileUrlTest() {
        // TODO: test fileUrl
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

}
