/*
 * Rainbow-API
 * The responses of the open api in swagger focus on the data field rather than the code and the message fields
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ModelsExposedMetadataAttribute
 */
public class ModelsExposedMetadataAttributeTest {
    private final ModelsExposedMetadataAttribute model = new ModelsExposedMetadataAttribute();

    /**
     * Model tests for ModelsExposedMetadataAttribute
     */
    @Test
    public void testModelsExposedMetadataAttribute() {
        // TODO: test ModelsExposedMetadataAttribute
    }

    /**
     * Test the property 'attributeName'
     */
    @Test
    public void attributeNameTest() {
        // TODO: test attributeName
    }

    /**
     * Test the property 'displayType'
     */
    @Test
    public void displayTypeTest() {
        // TODO: test displayType
    }

    /**
     * Test the property 'traitType'
     */
    @Test
    public void traitTypeTest() {
        // TODO: test traitType
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

}
