/*
 * Rainbow-API
 * The responses of the open api in swagger focus on the data field rather than the code and the message fields
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RainbowErrorsRainbowErrorDetailInfo
 */
public class RainbowErrorsRainbowErrorDetailInfoTest {
    private final RainbowErrorsRainbowErrorDetailInfo model = new RainbowErrorsRainbowErrorDetailInfo();

    /**
     * Model tests for RainbowErrorsRainbowErrorDetailInfo
     */
    @Test
    public void testRainbowErrorsRainbowErrorDetailInfo() {
        // TODO: test RainbowErrorsRainbowErrorDetailInfo
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

}
