/*
 * Rainbow-API
 * The responses of the open api in swagger focus on the data field rather than the code and the message fields
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ServicesCustomMintDto
 */
public class ServicesCustomMintDtoTest {
    private final ServicesCustomMintDto model = new ServicesCustomMintDto();

    /**
     * Model tests for ServicesCustomMintDto
     */
    @Test
    public void testServicesCustomMintDto() {
        // TODO: test ServicesCustomMintDto
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'chain'
     */
    @Test
    public void chainTest() {
        // TODO: test chain
    }

    /**
     * Test the property 'contractAddress'
     */
    @Test
    public void contractAddressTest() {
        // TODO: test contractAddress
    }

    /**
     * Test the property 'metadataUri'
     */
    @Test
    public void metadataUriTest() {
        // TODO: test metadataUri
    }

    /**
     * Test the property 'mintToAddress'
     */
    @Test
    public void mintToAddressTest() {
        // TODO: test mintToAddress
    }

    /**
     * Test the property 'tokenId'
     */
    @Test
    public void tokenIdTest() {
        // TODO: test tokenId
    }

}
