/*
 * Rainbow-API
 * The responses of the open api in swagger focus on the data field rather than the code and the message fields
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ServicesTxResp
 */
public class ServicesTxRespTest {
    private final ServicesTxResp model = new ServicesTxResp();

    /**
     * Model tests for ServicesTxResp
     */
    @Test
    public void testServicesTxResp() {
        // TODO: test ServicesTxResp
    }

    /**
     * Test the property 'errorMsg'
     */
    @Test
    public void errorMsgTest() {
        // TODO: test errorMsg
    }

    /**
     * Test the property 'hash'
     */
    @Test
    public void hashTest() {
        // TODO: test hash
    }

    /**
     * Test the property 'isFinalized'
     */
    @Test
    public void isFinalizedTest() {
        // TODO: test isFinalized
    }

    /**
     * Test the property 'isSuccess'
     */
    @Test
    public void isSuccessTest() {
        // TODO: test isSuccess
    }

    /**
     * Test the property 'stateCode'
     */
    @Test
    public void stateCodeTest() {
        // TODO: test stateCode
    }

    /**
     * Test the property 'stateMsg'
     */
    @Test
    public void stateMsgTest() {
        // TODO: test stateMsg
    }

}
