/*
 * Rainbow-API
 * The responses of the open api in swagger focus on the data field rather than the code and the message fields
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ServicesSendTxResp
 */
public class ServicesSendTxRespTest {
    private final ServicesSendTxResp model = new ServicesSendTxResp();

    /**
     * Model tests for ServicesSendTxResp
     */
    @Test
    public void testServicesSendTxResp() {
        // TODO: test ServicesSendTxResp
    }

    /**
     * Test the property 'txId'
     */
    @Test
    public void txIdTest() {
        // TODO: test txId
    }

}
