/*
 * Rainbow-API
 * The responses of the open api in swagger focus on the data field rather than the code and the message fields
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ServicesTransferDto
 */
public class ServicesTransferDtoTest {
    private final ServicesTransferDto model = new ServicesTransferDto();

    /**
     * Model tests for ServicesTransferDto
     */
    @Test
    public void testServicesTransferDto() {
        // TODO: test ServicesTransferDto
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'chain'
     */
    @Test
    public void chainTest() {
        // TODO: test chain
    }

    /**
     * Test the property 'contractAddress'
     */
    @Test
    public void contractAddressTest() {
        // TODO: test contractAddress
    }

    /**
     * Test the property 'contractType'
     */
    @Test
    public void contractTypeTest() {
        // TODO: test contractType
    }

    /**
     * Test the property 'tokenId'
     */
    @Test
    public void tokenIdTest() {
        // TODO: test tokenId
    }

    /**
     * Test the property 'transferFromAddress'
     */
    @Test
    public void transferFromAddressTest() {
        // TODO: test transferFromAddress
    }

    /**
     * Test the property 'transferToAddress'
     */
    @Test
    public void transferToAddressTest() {
        // TODO: test transferToAddress
    }

}
