/*
 * Rainbow-API
 * The responses of the open api in swagger focus on the data field rather than the code and the message fields
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ServicesSponsorInfo
 */
public class ServicesSponsorInfoTest {
    private final ServicesSponsorInfo model = new ServicesSponsorInfo();

    /**
     * Model tests for ServicesSponsorInfo
     */
    @Test
    public void testServicesSponsorInfo() {
        // TODO: test ServicesSponsorInfo
    }

    /**
     * Test the property 'collateralSponsor'
     */
    @Test
    public void collateralSponsorTest() {
        // TODO: test collateralSponsor
    }

    /**
     * Test the property 'collateralSponsorBalance'
     */
    @Test
    public void collateralSponsorBalanceTest() {
        // TODO: test collateralSponsorBalance
    }

    /**
     * Test the property 'gasSponsor'
     */
    @Test
    public void gasSponsorTest() {
        // TODO: test gasSponsor
    }

    /**
     * Test the property 'gasSponsorBalance'
     */
    @Test
    public void gasSponsorBalanceTest() {
        // TODO: test gasSponsorBalance
    }

    /**
     * Test the property 'gasUpperBound'
     */
    @Test
    public void gasUpperBoundTest() {
        // TODO: test gasUpperBound
    }

    /**
     * Test the property 'isAllWhiteListed'
     */
    @Test
    public void isAllWhiteListedTest() {
        // TODO: test isAllWhiteListed
    }

}
