/*
 * Rainbow-API
 * The responses of the open api in swagger focus on the data field rather than the code and the message fields
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * MiddlewaresLoginResp
 */
@JsonPropertyOrder({
  MiddlewaresLoginResp.JSON_PROPERTY_EXPIRE,
  MiddlewaresLoginResp.JSON_PROPERTY_TOKEN
})
@JsonTypeName("middlewares.LoginResp")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class MiddlewaresLoginResp {
  public static final String JSON_PROPERTY_EXPIRE = "expire";
  private String expire;

  public static final String JSON_PROPERTY_TOKEN = "token";
  private String token;

  public MiddlewaresLoginResp() {
  }

  public MiddlewaresLoginResp expire(String expire) {
    
    this.expire = expire;
    return this;
  }

   /**
   * Get expire
   * @return expire
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EXPIRE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExpire() {
    return expire;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpire(String expire) {
    this.expire = expire;
  }


  public MiddlewaresLoginResp token(String token) {
    
    this.token = token;
    return this;
  }

   /**
   * Get token
   * @return token
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getToken() {
    return token;
  }


  @JsonProperty(JSON_PROPERTY_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToken(String token) {
    this.token = token;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MiddlewaresLoginResp middlewaresLoginResp = (MiddlewaresLoginResp) o;
    return Objects.equals(this.expire, middlewaresLoginResp.expire) &&
        Objects.equals(this.token, middlewaresLoginResp.token);
  }

  @Override
  public int hashCode() {
    return Objects.hash(expire, token);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MiddlewaresLoginResp {\n");
    sb.append("    expire: ").append(toIndentedString(expire)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

