/*
 * Rainbow-API
 * The responses of the open api in swagger focus on the data field rather than the code and the message fields
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ModelsExposedMetadataAttribute
 */
@JsonPropertyOrder({
  ModelsExposedMetadataAttribute.JSON_PROPERTY_ATTRIBUTE_NAME,
  ModelsExposedMetadataAttribute.JSON_PROPERTY_DISPLAY_TYPE,
  ModelsExposedMetadataAttribute.JSON_PROPERTY_TRAIT_TYPE,
  ModelsExposedMetadataAttribute.JSON_PROPERTY_VALUE
})
@JsonTypeName("models.ExposedMetadataAttribute")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ModelsExposedMetadataAttribute {
  public static final String JSON_PROPERTY_ATTRIBUTE_NAME = "attribute_name";
  private String attributeName;

  public static final String JSON_PROPERTY_DISPLAY_TYPE = "display_type";
  private String displayType;

  public static final String JSON_PROPERTY_TRAIT_TYPE = "trait_type";
  private String traitType;

  public static final String JSON_PROPERTY_VALUE = "value";
  private String value;

  public ModelsExposedMetadataAttribute() {
  }

  public ModelsExposedMetadataAttribute attributeName(String attributeName) {
    
    this.attributeName = attributeName;
    return this;
  }

   /**
   * Get attributeName
   * @return attributeName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ATTRIBUTE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAttributeName() {
    return attributeName;
  }


  @JsonProperty(JSON_PROPERTY_ATTRIBUTE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAttributeName(String attributeName) {
    this.attributeName = attributeName;
  }


  public ModelsExposedMetadataAttribute displayType(String displayType) {
    
    this.displayType = displayType;
    return this;
  }

   /**
   * Get displayType
   * @return displayType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DISPLAY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDisplayType() {
    return displayType;
  }


  @JsonProperty(JSON_PROPERTY_DISPLAY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisplayType(String displayType) {
    this.displayType = displayType;
  }


  public ModelsExposedMetadataAttribute traitType(String traitType) {
    
    this.traitType = traitType;
    return this;
  }

   /**
   * Get traitType
   * @return traitType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TRAIT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTraitType() {
    return traitType;
  }


  @JsonProperty(JSON_PROPERTY_TRAIT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTraitType(String traitType) {
    this.traitType = traitType;
  }


  public ModelsExposedMetadataAttribute value(String value) {
    
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getValue() {
    return value;
  }


  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelsExposedMetadataAttribute modelsExposedMetadataAttribute = (ModelsExposedMetadataAttribute) o;
    return Objects.equals(this.attributeName, modelsExposedMetadataAttribute.attributeName) &&
        Objects.equals(this.displayType, modelsExposedMetadataAttribute.displayType) &&
        Objects.equals(this.traitType, modelsExposedMetadataAttribute.traitType) &&
        Objects.equals(this.value, modelsExposedMetadataAttribute.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attributeName, displayType, traitType, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelsExposedMetadataAttribute {\n");
    sb.append("    attributeName: ").append(toIndentedString(attributeName)).append("\n");
    sb.append("    displayType: ").append(toIndentedString(displayType)).append("\n");
    sb.append("    traitType: ").append(toIndentedString(traitType)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

