/*
 * Rainbow-API
 * The responses of the open api in swagger focus on the data field rather than the code and the message fields
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.GormDeletedAt;
import org.openapitools.client.model.ModelsExposedMetadataAttribute;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ModelsExposedMetadata
 */
@JsonPropertyOrder({
  ModelsExposedMetadata.JSON_PROPERTY_ANIMATION_URL,
  ModelsExposedMetadata.JSON_PROPERTY_ATTRIBUTES,
  ModelsExposedMetadata.JSON_PROPERTY_CREATED_AT,
  ModelsExposedMetadata.JSON_PROPERTY_DELETED_AT,
  ModelsExposedMetadata.JSON_PROPERTY_DESCRIPTION,
  ModelsExposedMetadata.JSON_PROPERTY_EXTERNAL_LINK,
  ModelsExposedMetadata.JSON_PROPERTY_ID,
  ModelsExposedMetadata.JSON_PROPERTY_IMAGE,
  ModelsExposedMetadata.JSON_PROPERTY_METADATA_ID,
  ModelsExposedMetadata.JSON_PROPERTY_NAME,
  ModelsExposedMetadata.JSON_PROPERTY_UPDATED_AT,
  ModelsExposedMetadata.JSON_PROPERTY_URI
})
@JsonTypeName("models.ExposedMetadata")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ModelsExposedMetadata {
  public static final String JSON_PROPERTY_ANIMATION_URL = "animation_url";
  private String animationUrl;

  public static final String JSON_PROPERTY_ATTRIBUTES = "attributes";
  private List<ModelsExposedMetadataAttribute> attributes = null;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  private String createdAt;

  public static final String JSON_PROPERTY_DELETED_AT = "deleted_at";
  private GormDeletedAt deletedAt;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_EXTERNAL_LINK = "external_link";
  private String externalLink;

  public static final String JSON_PROPERTY_ID = "id";
  private Integer id;

  public static final String JSON_PROPERTY_IMAGE = "image";
  private String image;

  public static final String JSON_PROPERTY_METADATA_ID = "metadata_id";
  private String metadataId;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated_at";
  private String updatedAt;

  public static final String JSON_PROPERTY_URI = "uri";
  private String uri;

  public ModelsExposedMetadata() {
  }

  public ModelsExposedMetadata animationUrl(String animationUrl) {
    
    this.animationUrl = animationUrl;
    return this;
  }

   /**
   * Get animationUrl
   * @return animationUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ANIMATION_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAnimationUrl() {
    return animationUrl;
  }


  @JsonProperty(JSON_PROPERTY_ANIMATION_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAnimationUrl(String animationUrl) {
    this.animationUrl = animationUrl;
  }


  public ModelsExposedMetadata attributes(List<ModelsExposedMetadataAttribute> attributes) {
    
    this.attributes = attributes;
    return this;
  }

  public ModelsExposedMetadata addAttributesItem(ModelsExposedMetadataAttribute attributesItem) {
    if (this.attributes == null) {
      this.attributes = new ArrayList<>();
    }
    this.attributes.add(attributesItem);
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ModelsExposedMetadataAttribute> getAttributes() {
    return attributes;
  }


  @JsonProperty(JSON_PROPERTY_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAttributes(List<ModelsExposedMetadataAttribute> attributes) {
    this.attributes = attributes;
  }


  public ModelsExposedMetadata createdAt(String createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }


  public ModelsExposedMetadata deletedAt(GormDeletedAt deletedAt) {
    
    this.deletedAt = deletedAt;
    return this;
  }

   /**
   * Get deletedAt
   * @return deletedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GormDeletedAt getDeletedAt() {
    return deletedAt;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedAt(GormDeletedAt deletedAt) {
    this.deletedAt = deletedAt;
  }


  public ModelsExposedMetadata description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDescription(String description) {
    this.description = description;
  }


  public ModelsExposedMetadata externalLink(String externalLink) {
    
    this.externalLink = externalLink;
    return this;
  }

   /**
   * Get externalLink
   * @return externalLink
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EXTERNAL_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExternalLink() {
    return externalLink;
  }


  @JsonProperty(JSON_PROPERTY_EXTERNAL_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExternalLink(String externalLink) {
    this.externalLink = externalLink;
  }


  public ModelsExposedMetadata id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Integer id) {
    this.id = id;
  }


  public ModelsExposedMetadata image(String image) {
    
    this.image = image;
    return this;
  }

   /**
   * Get image
   * @return image
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_IMAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getImage() {
    return image;
  }


  @JsonProperty(JSON_PROPERTY_IMAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setImage(String image) {
    this.image = image;
  }


  public ModelsExposedMetadata metadataId(String metadataId) {
    
    this.metadataId = metadataId;
    return this;
  }

   /**
   * Get metadataId
   * @return metadataId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_METADATA_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMetadataId() {
    return metadataId;
  }


  @JsonProperty(JSON_PROPERTY_METADATA_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadataId(String metadataId) {
    this.metadataId = metadataId;
  }


  public ModelsExposedMetadata name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  public ModelsExposedMetadata updatedAt(String updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  public ModelsExposedMetadata uri(String uri) {
    
    this.uri = uri;
    return this;
  }

   /**
   * Get uri
   * @return uri
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUri() {
    return uri;
  }


  @JsonProperty(JSON_PROPERTY_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUri(String uri) {
    this.uri = uri;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelsExposedMetadata modelsExposedMetadata = (ModelsExposedMetadata) o;
    return Objects.equals(this.animationUrl, modelsExposedMetadata.animationUrl) &&
        Objects.equals(this.attributes, modelsExposedMetadata.attributes) &&
        Objects.equals(this.createdAt, modelsExposedMetadata.createdAt) &&
        Objects.equals(this.deletedAt, modelsExposedMetadata.deletedAt) &&
        Objects.equals(this.description, modelsExposedMetadata.description) &&
        Objects.equals(this.externalLink, modelsExposedMetadata.externalLink) &&
        Objects.equals(this.id, modelsExposedMetadata.id) &&
        Objects.equals(this.image, modelsExposedMetadata.image) &&
        Objects.equals(this.metadataId, modelsExposedMetadata.metadataId) &&
        Objects.equals(this.name, modelsExposedMetadata.name) &&
        Objects.equals(this.updatedAt, modelsExposedMetadata.updatedAt) &&
        Objects.equals(this.uri, modelsExposedMetadata.uri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(animationUrl, attributes, createdAt, deletedAt, description, externalLink, id, image, metadataId, name, updatedAt, uri);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelsExposedMetadata {\n");
    sb.append("    animationUrl: ").append(toIndentedString(animationUrl)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    externalLink: ").append(toIndentedString(externalLink)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    metadataId: ").append(toIndentedString(metadataId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

