/*
 * Rainbow-API
 * The responses of the open api in swagger focus on the data field rather than the code and the message fields
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.client.model.GormDeletedAt;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ModelsContract
 */
@JsonPropertyOrder({
  ModelsContract.JSON_PROPERTY_ADDRESS,
  ModelsContract.JSON_PROPERTY_APP_ID,
  ModelsContract.JSON_PROPERTY_BASE_URI,
  ModelsContract.JSON_PROPERTY_CHAIN_ID,
  ModelsContract.JSON_PROPERTY_CHAIN_TYPE,
  ModelsContract.JSON_PROPERTY_CREATED_AT,
  ModelsContract.JSON_PROPERTY_DELETED_AT,
  ModelsContract.JSON_PROPERTY_HASH,
  ModelsContract.JSON_PROPERTY_ID,
  ModelsContract.JSON_PROPERTY_NAME,
  ModelsContract.JSON_PROPERTY_OWNER_ADDRESS,
  ModelsContract.JSON_PROPERTY_ROYALTIES_ADDRESS,
  ModelsContract.JSON_PROPERTY_ROYALTIES_BPS,
  ModelsContract.JSON_PROPERTY_STATUS,
  ModelsContract.JSON_PROPERTY_SYMBOL,
  ModelsContract.JSON_PROPERTY_TOKENS_BURNABLE,
  ModelsContract.JSON_PROPERTY_TOKENS_TRANSFERABLE_BY_ADMIN,
  ModelsContract.JSON_PROPERTY_TOKENS_TRANSFERABLE_BY_USER,
  ModelsContract.JSON_PROPERTY_TRANSFER_COOLDOWN_TIME,
  ModelsContract.JSON_PROPERTY_TX_ID,
  ModelsContract.JSON_PROPERTY_TYPE,
  ModelsContract.JSON_PROPERTY_UPDATED_AT
})
@JsonTypeName("models.Contract")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ModelsContract {
  public static final String JSON_PROPERTY_ADDRESS = "address";
  private String address;

  public static final String JSON_PROPERTY_APP_ID = "app_id";
  private Integer appId;

  public static final String JSON_PROPERTY_BASE_URI = "base_uri";
  private String baseUri;

  public static final String JSON_PROPERTY_CHAIN_ID = "chain_id";
  private Integer chainId;

  public static final String JSON_PROPERTY_CHAIN_TYPE = "chain_type";
  private Integer chainType;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  private String createdAt;

  public static final String JSON_PROPERTY_DELETED_AT = "deleted_at";
  private GormDeletedAt deletedAt;

  public static final String JSON_PROPERTY_HASH = "hash";
  private String hash;

  public static final String JSON_PROPERTY_ID = "id";
  private Integer id;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_OWNER_ADDRESS = "owner_address";
  private String ownerAddress;

  public static final String JSON_PROPERTY_ROYALTIES_ADDRESS = "royalties_address";
  private String royaltiesAddress;

  public static final String JSON_PROPERTY_ROYALTIES_BPS = "royalties_bps";
  private Integer royaltiesBps;

  public static final String JSON_PROPERTY_STATUS = "status";
  private Integer status;

  public static final String JSON_PROPERTY_SYMBOL = "symbol";
  private String symbol;

  public static final String JSON_PROPERTY_TOKENS_BURNABLE = "tokens_burnable";
  private Boolean tokensBurnable;

  public static final String JSON_PROPERTY_TOKENS_TRANSFERABLE_BY_ADMIN = "tokens_transferable_by_admin";
  private Boolean tokensTransferableByAdmin;

  public static final String JSON_PROPERTY_TOKENS_TRANSFERABLE_BY_USER = "tokens_transferable_by_user";
  private Boolean tokensTransferableByUser;

  public static final String JSON_PROPERTY_TRANSFER_COOLDOWN_TIME = "transfer_cooldown_time";
  private Integer transferCooldownTime;

  public static final String JSON_PROPERTY_TX_ID = "tx_id";
  private Integer txId;

  public static final String JSON_PROPERTY_TYPE = "type";
  private Integer type;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated_at";
  private String updatedAt;

  public ModelsContract() {
  }

  public ModelsContract address(String address) {
    
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddress() {
    return address;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddress(String address) {
    this.address = address;
  }


  public ModelsContract appId(Integer appId) {
    
    this.appId = appId;
    return this;
  }

   /**
   * Get appId
   * @return appId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_APP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAppId() {
    return appId;
  }


  @JsonProperty(JSON_PROPERTY_APP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAppId(Integer appId) {
    this.appId = appId;
  }


  public ModelsContract baseUri(String baseUri) {
    
    this.baseUri = baseUri;
    return this;
  }

   /**
   * Get baseUri
   * @return baseUri
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_BASE_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBaseUri() {
    return baseUri;
  }


  @JsonProperty(JSON_PROPERTY_BASE_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBaseUri(String baseUri) {
    this.baseUri = baseUri;
  }


  public ModelsContract chainId(Integer chainId) {
    
    this.chainId = chainId;
    return this;
  }

   /**
   * Get chainId
   * @return chainId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CHAIN_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getChainId() {
    return chainId;
  }


  @JsonProperty(JSON_PROPERTY_CHAIN_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChainId(Integer chainId) {
    this.chainId = chainId;
  }


  public ModelsContract chainType(Integer chainType) {
    
    this.chainType = chainType;
    return this;
  }

   /**
   * Get chainType
   * @return chainType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CHAIN_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getChainType() {
    return chainType;
  }


  @JsonProperty(JSON_PROPERTY_CHAIN_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChainType(Integer chainType) {
    this.chainType = chainType;
  }


  public ModelsContract createdAt(String createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }


  public ModelsContract deletedAt(GormDeletedAt deletedAt) {
    
    this.deletedAt = deletedAt;
    return this;
  }

   /**
   * Get deletedAt
   * @return deletedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GormDeletedAt getDeletedAt() {
    return deletedAt;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedAt(GormDeletedAt deletedAt) {
    this.deletedAt = deletedAt;
  }


  public ModelsContract hash(String hash) {
    
    this.hash = hash;
    return this;
  }

   /**
   * Get hash
   * @return hash
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_HASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHash() {
    return hash;
  }


  @JsonProperty(JSON_PROPERTY_HASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHash(String hash) {
    this.hash = hash;
  }


  public ModelsContract id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Integer id) {
    this.id = id;
  }


  public ModelsContract name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public ModelsContract ownerAddress(String ownerAddress) {
    
    this.ownerAddress = ownerAddress;
    return this;
  }

   /**
   * Get ownerAddress
   * @return ownerAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_OWNER_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOwnerAddress() {
    return ownerAddress;
  }


  @JsonProperty(JSON_PROPERTY_OWNER_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOwnerAddress(String ownerAddress) {
    this.ownerAddress = ownerAddress;
  }


  public ModelsContract royaltiesAddress(String royaltiesAddress) {
    
    this.royaltiesAddress = royaltiesAddress;
    return this;
  }

   /**
   * Get royaltiesAddress
   * @return royaltiesAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ROYALTIES_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRoyaltiesAddress() {
    return royaltiesAddress;
  }


  @JsonProperty(JSON_PROPERTY_ROYALTIES_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRoyaltiesAddress(String royaltiesAddress) {
    this.royaltiesAddress = royaltiesAddress;
  }


  public ModelsContract royaltiesBps(Integer royaltiesBps) {
    
    this.royaltiesBps = royaltiesBps;
    return this;
  }

   /**
   * Get royaltiesBps
   * @return royaltiesBps
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ROYALTIES_BPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRoyaltiesBps() {
    return royaltiesBps;
  }


  @JsonProperty(JSON_PROPERTY_ROYALTIES_BPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRoyaltiesBps(Integer royaltiesBps) {
    this.royaltiesBps = royaltiesBps;
  }


  public ModelsContract status(Integer status) {
    
    this.status = status;
    return this;
  }

   /**
   * 0-pending, 1-success, 2-failed
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "0-pending, 1-success, 2-failed")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(Integer status) {
    this.status = status;
  }


  public ModelsContract symbol(String symbol) {
    
    this.symbol = symbol;
    return this;
  }

   /**
   * Get symbol
   * @return symbol
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSymbol() {
    return symbol;
  }


  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }


  public ModelsContract tokensBurnable(Boolean tokensBurnable) {
    
    this.tokensBurnable = tokensBurnable;
    return this;
  }

   /**
   * Get tokensBurnable
   * @return tokensBurnable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOKENS_BURNABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getTokensBurnable() {
    return tokensBurnable;
  }


  @JsonProperty(JSON_PROPERTY_TOKENS_BURNABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTokensBurnable(Boolean tokensBurnable) {
    this.tokensBurnable = tokensBurnable;
  }


  public ModelsContract tokensTransferableByAdmin(Boolean tokensTransferableByAdmin) {
    
    this.tokensTransferableByAdmin = tokensTransferableByAdmin;
    return this;
  }

   /**
   * Get tokensTransferableByAdmin
   * @return tokensTransferableByAdmin
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOKENS_TRANSFERABLE_BY_ADMIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getTokensTransferableByAdmin() {
    return tokensTransferableByAdmin;
  }


  @JsonProperty(JSON_PROPERTY_TOKENS_TRANSFERABLE_BY_ADMIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTokensTransferableByAdmin(Boolean tokensTransferableByAdmin) {
    this.tokensTransferableByAdmin = tokensTransferableByAdmin;
  }


  public ModelsContract tokensTransferableByUser(Boolean tokensTransferableByUser) {
    
    this.tokensTransferableByUser = tokensTransferableByUser;
    return this;
  }

   /**
   * Get tokensTransferableByUser
   * @return tokensTransferableByUser
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOKENS_TRANSFERABLE_BY_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getTokensTransferableByUser() {
    return tokensTransferableByUser;
  }


  @JsonProperty(JSON_PROPERTY_TOKENS_TRANSFERABLE_BY_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTokensTransferableByUser(Boolean tokensTransferableByUser) {
    this.tokensTransferableByUser = tokensTransferableByUser;
  }


  public ModelsContract transferCooldownTime(Integer transferCooldownTime) {
    
    this.transferCooldownTime = transferCooldownTime;
    return this;
  }

   /**
   * Get transferCooldownTime
   * @return transferCooldownTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TRANSFER_COOLDOWN_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTransferCooldownTime() {
    return transferCooldownTime;
  }


  @JsonProperty(JSON_PROPERTY_TRANSFER_COOLDOWN_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransferCooldownTime(Integer transferCooldownTime) {
    this.transferCooldownTime = transferCooldownTime;
  }


  public ModelsContract txId(Integer txId) {
    
    this.txId = txId;
    return this;
  }

   /**
   * Get txId
   * @return txId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TX_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTxId() {
    return txId;
  }


  @JsonProperty(JSON_PROPERTY_TX_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTxId(Integer txId) {
    this.txId = txId;
  }


  public ModelsContract type(Integer type) {
    
    this.type = type;
    return this;
  }

   /**
   * 1-ERC721, 2-ERC1155
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "1-ERC721, 2-ERC1155")
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(Integer type) {
    this.type = type;
  }


  public ModelsContract updatedAt(String updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelsContract modelsContract = (ModelsContract) o;
    return Objects.equals(this.address, modelsContract.address) &&
        Objects.equals(this.appId, modelsContract.appId) &&
        Objects.equals(this.baseUri, modelsContract.baseUri) &&
        Objects.equals(this.chainId, modelsContract.chainId) &&
        Objects.equals(this.chainType, modelsContract.chainType) &&
        Objects.equals(this.createdAt, modelsContract.createdAt) &&
        Objects.equals(this.deletedAt, modelsContract.deletedAt) &&
        Objects.equals(this.hash, modelsContract.hash) &&
        Objects.equals(this.id, modelsContract.id) &&
        Objects.equals(this.name, modelsContract.name) &&
        Objects.equals(this.ownerAddress, modelsContract.ownerAddress) &&
        Objects.equals(this.royaltiesAddress, modelsContract.royaltiesAddress) &&
        Objects.equals(this.royaltiesBps, modelsContract.royaltiesBps) &&
        Objects.equals(this.status, modelsContract.status) &&
        Objects.equals(this.symbol, modelsContract.symbol) &&
        Objects.equals(this.tokensBurnable, modelsContract.tokensBurnable) &&
        Objects.equals(this.tokensTransferableByAdmin, modelsContract.tokensTransferableByAdmin) &&
        Objects.equals(this.tokensTransferableByUser, modelsContract.tokensTransferableByUser) &&
        Objects.equals(this.transferCooldownTime, modelsContract.transferCooldownTime) &&
        Objects.equals(this.txId, modelsContract.txId) &&
        Objects.equals(this.type, modelsContract.type) &&
        Objects.equals(this.updatedAt, modelsContract.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, appId, baseUri, chainId, chainType, createdAt, deletedAt, hash, id, name, ownerAddress, royaltiesAddress, royaltiesBps, status, symbol, tokensBurnable, tokensTransferableByAdmin, tokensTransferableByUser, transferCooldownTime, txId, type, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelsContract {\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    appId: ").append(toIndentedString(appId)).append("\n");
    sb.append("    baseUri: ").append(toIndentedString(baseUri)).append("\n");
    sb.append("    chainId: ").append(toIndentedString(chainId)).append("\n");
    sb.append("    chainType: ").append(toIndentedString(chainType)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    hash: ").append(toIndentedString(hash)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    ownerAddress: ").append(toIndentedString(ownerAddress)).append("\n");
    sb.append("    royaltiesAddress: ").append(toIndentedString(royaltiesAddress)).append("\n");
    sb.append("    royaltiesBps: ").append(toIndentedString(royaltiesBps)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    tokensBurnable: ").append(toIndentedString(tokensBurnable)).append("\n");
    sb.append("    tokensTransferableByAdmin: ").append(toIndentedString(tokensTransferableByAdmin)).append("\n");
    sb.append("    tokensTransferableByUser: ").append(toIndentedString(tokensTransferableByUser)).append("\n");
    sb.append("    transferCooldownTime: ").append(toIndentedString(transferCooldownTime)).append("\n");
    sb.append("    txId: ").append(toIndentedString(txId)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

