/*
 * Rainbow-API
 * The responses of the open api in swagger focus on the data field rather than the code and the message fields
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ServicesEasyMintMetaDto
 */
@JsonPropertyOrder({
  ServicesEasyMintMetaDto.JSON_PROPERTY_CHAIN,
  ServicesEasyMintMetaDto.JSON_PROPERTY_DESCRIPTION,
  ServicesEasyMintMetaDto.JSON_PROPERTY_FILE_URL,
  ServicesEasyMintMetaDto.JSON_PROPERTY_MINT_TO_ADDRESS,
  ServicesEasyMintMetaDto.JSON_PROPERTY_NAME
})
@JsonTypeName("services.EasyMintMetaDto")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ServicesEasyMintMetaDto {
  public static final String JSON_PROPERTY_CHAIN = "chain";
  private String chain;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_FILE_URL = "file_url";
  private String fileUrl;

  public static final String JSON_PROPERTY_MINT_TO_ADDRESS = "mint_to_address";
  private String mintToAddress;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public ServicesEasyMintMetaDto() {
  }

  public ServicesEasyMintMetaDto chain(String chain) {
    
    this.chain = chain;
    return this;
  }

   /**
   * Get chain
   * @return chain
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CHAIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getChain() {
    return chain;
  }


  @JsonProperty(JSON_PROPERTY_CHAIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setChain(String chain) {
    this.chain = chain;
  }


  public ServicesEasyMintMetaDto description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDescription(String description) {
    this.description = description;
  }


  public ServicesEasyMintMetaDto fileUrl(String fileUrl) {
    
    this.fileUrl = fileUrl;
    return this;
  }

   /**
   * Get fileUrl
   * @return fileUrl
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_FILE_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFileUrl() {
    return fileUrl;
  }


  @JsonProperty(JSON_PROPERTY_FILE_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFileUrl(String fileUrl) {
    this.fileUrl = fileUrl;
  }


  public ServicesEasyMintMetaDto mintToAddress(String mintToAddress) {
    
    this.mintToAddress = mintToAddress;
    return this;
  }

   /**
   * Get mintToAddress
   * @return mintToAddress
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_MINT_TO_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMintToAddress() {
    return mintToAddress;
  }


  @JsonProperty(JSON_PROPERTY_MINT_TO_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMintToAddress(String mintToAddress) {
    this.mintToAddress = mintToAddress;
  }


  public ServicesEasyMintMetaDto name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServicesEasyMintMetaDto servicesEasyMintMetaDto = (ServicesEasyMintMetaDto) o;
    return Objects.equals(this.chain, servicesEasyMintMetaDto.chain) &&
        Objects.equals(this.description, servicesEasyMintMetaDto.description) &&
        Objects.equals(this.fileUrl, servicesEasyMintMetaDto.fileUrl) &&
        Objects.equals(this.mintToAddress, servicesEasyMintMetaDto.mintToAddress) &&
        Objects.equals(this.name, servicesEasyMintMetaDto.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(chain, description, fileUrl, mintToAddress, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServicesEasyMintMetaDto {\n");
    sb.append("    chain: ").append(toIndentedString(chain)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    fileUrl: ").append(toIndentedString(fileUrl)).append("\n");
    sb.append("    mintToAddress: ").append(toIndentedString(mintToAddress)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

