/*
 * Rainbow-API
 * The responses of the open api in swagger focus on the data field rather than the code and the message fields
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ServicesCustomMintDto
 */
@JsonPropertyOrder({
  ServicesCustomMintDto.JSON_PROPERTY_AMOUNT,
  ServicesCustomMintDto.JSON_PROPERTY_CHAIN,
  ServicesCustomMintDto.JSON_PROPERTY_CONTRACT_ADDRESS,
  ServicesCustomMintDto.JSON_PROPERTY_METADATA_URI,
  ServicesCustomMintDto.JSON_PROPERTY_MINT_TO_ADDRESS,
  ServicesCustomMintDto.JSON_PROPERTY_TOKEN_ID
})
@JsonTypeName("services.CustomMintDto")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ServicesCustomMintDto {
  public static final String JSON_PROPERTY_AMOUNT = "amount";
  private Integer amount;

  /**
   * Gets or Sets chain
   */
  public enum ChainEnum {
    CONFLUX("conflux"),
    
    CONFLUX_TEST("conflux_test");

    private String value;

    ChainEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ChainEnum fromValue(String value) {
      for (ChainEnum b : ChainEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_CHAIN = "chain";
  private ChainEnum chain;

  public static final String JSON_PROPERTY_CONTRACT_ADDRESS = "contract_address";
  private String contractAddress;

  public static final String JSON_PROPERTY_METADATA_URI = "metadata_uri";
  private String metadataUri;

  public static final String JSON_PROPERTY_MINT_TO_ADDRESS = "mint_to_address";
  private String mintToAddress;

  public static final String JSON_PROPERTY_TOKEN_ID = "token_id";
  private String tokenId;

  public ServicesCustomMintDto() {
  }

  public ServicesCustomMintDto amount(Integer amount) {
    
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAmount() {
    return amount;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAmount(Integer amount) {
    this.amount = amount;
  }


  public ServicesCustomMintDto chain(ChainEnum chain) {
    
    this.chain = chain;
    return this;
  }

   /**
   * Get chain
   * @return chain
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CHAIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ChainEnum getChain() {
    return chain;
  }


  @JsonProperty(JSON_PROPERTY_CHAIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setChain(ChainEnum chain) {
    this.chain = chain;
  }


  public ServicesCustomMintDto contractAddress(String contractAddress) {
    
    this.contractAddress = contractAddress;
    return this;
  }

   /**
   * Get contractAddress
   * @return contractAddress
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CONTRACT_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getContractAddress() {
    return contractAddress;
  }


  @JsonProperty(JSON_PROPERTY_CONTRACT_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContractAddress(String contractAddress) {
    this.contractAddress = contractAddress;
  }


  public ServicesCustomMintDto metadataUri(String metadataUri) {
    
    this.metadataUri = metadataUri;
    return this;
  }

   /**
   * Get metadataUri
   * @return metadataUri
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_METADATA_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMetadataUri() {
    return metadataUri;
  }


  @JsonProperty(JSON_PROPERTY_METADATA_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadataUri(String metadataUri) {
    this.metadataUri = metadataUri;
  }


  public ServicesCustomMintDto mintToAddress(String mintToAddress) {
    
    this.mintToAddress = mintToAddress;
    return this;
  }

   /**
   * Get mintToAddress
   * @return mintToAddress
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_MINT_TO_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMintToAddress() {
    return mintToAddress;
  }


  @JsonProperty(JSON_PROPERTY_MINT_TO_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMintToAddress(String mintToAddress) {
    this.mintToAddress = mintToAddress;
  }


  public ServicesCustomMintDto tokenId(String tokenId) {
    
    this.tokenId = tokenId;
    return this;
  }

   /**
   * Get tokenId
   * @return tokenId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOKEN_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTokenId() {
    return tokenId;
  }


  @JsonProperty(JSON_PROPERTY_TOKEN_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTokenId(String tokenId) {
    this.tokenId = tokenId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServicesCustomMintDto servicesCustomMintDto = (ServicesCustomMintDto) o;
    return Objects.equals(this.amount, servicesCustomMintDto.amount) &&
        Objects.equals(this.chain, servicesCustomMintDto.chain) &&
        Objects.equals(this.contractAddress, servicesCustomMintDto.contractAddress) &&
        Objects.equals(this.metadataUri, servicesCustomMintDto.metadataUri) &&
        Objects.equals(this.mintToAddress, servicesCustomMintDto.mintToAddress) &&
        Objects.equals(this.tokenId, servicesCustomMintDto.tokenId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, chain, contractAddress, metadataUri, mintToAddress, tokenId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServicesCustomMintDto {\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    chain: ").append(toIndentedString(chain)).append("\n");
    sb.append("    contractAddress: ").append(toIndentedString(contractAddress)).append("\n");
    sb.append("    metadataUri: ").append(toIndentedString(metadataUri)).append("\n");
    sb.append("    mintToAddress: ").append(toIndentedString(mintToAddress)).append("\n");
    sb.append("    tokenId: ").append(toIndentedString(tokenId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

