/*
 * Rainbow-API
 * The responses of the open api in swagger focus on the data field rather than the code and the message fields
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ServicesMintItemDto;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ServicesCustomMintBatchDto
 */
@JsonPropertyOrder({
  ServicesCustomMintBatchDto.JSON_PROPERTY_CHAIN,
  ServicesCustomMintBatchDto.JSON_PROPERTY_CONTRACT_ADDRESS,
  ServicesCustomMintBatchDto.JSON_PROPERTY_MINT_ITEMS
})
@JsonTypeName("services.CustomMintBatchDto")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ServicesCustomMintBatchDto {
  /**
   * Gets or Sets chain
   */
  public enum ChainEnum {
    CONFLUX("conflux"),
    
    CONFLUX_TEST("conflux_test");

    private String value;

    ChainEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ChainEnum fromValue(String value) {
      for (ChainEnum b : ChainEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_CHAIN = "chain";
  private ChainEnum chain;

  public static final String JSON_PROPERTY_CONTRACT_ADDRESS = "contract_address";
  private String contractAddress;

  public static final String JSON_PROPERTY_MINT_ITEMS = "mint_items";
  private List<ServicesMintItemDto> mintItems = new ArrayList<>();

  public ServicesCustomMintBatchDto() {
  }

  public ServicesCustomMintBatchDto chain(ChainEnum chain) {
    
    this.chain = chain;
    return this;
  }

   /**
   * Get chain
   * @return chain
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CHAIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ChainEnum getChain() {
    return chain;
  }


  @JsonProperty(JSON_PROPERTY_CHAIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setChain(ChainEnum chain) {
    this.chain = chain;
  }


  public ServicesCustomMintBatchDto contractAddress(String contractAddress) {
    
    this.contractAddress = contractAddress;
    return this;
  }

   /**
   * Get contractAddress
   * @return contractAddress
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CONTRACT_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getContractAddress() {
    return contractAddress;
  }


  @JsonProperty(JSON_PROPERTY_CONTRACT_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContractAddress(String contractAddress) {
    this.contractAddress = contractAddress;
  }


  public ServicesCustomMintBatchDto mintItems(List<ServicesMintItemDto> mintItems) {
    
    this.mintItems = mintItems;
    return this;
  }

  public ServicesCustomMintBatchDto addMintItemsItem(ServicesMintItemDto mintItemsItem) {
    this.mintItems.add(mintItemsItem);
    return this;
  }

   /**
   * Get mintItems
   * @return mintItems
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_MINT_ITEMS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<ServicesMintItemDto> getMintItems() {
    return mintItems;
  }


  @JsonProperty(JSON_PROPERTY_MINT_ITEMS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMintItems(List<ServicesMintItemDto> mintItems) {
    this.mintItems = mintItems;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServicesCustomMintBatchDto servicesCustomMintBatchDto = (ServicesCustomMintBatchDto) o;
    return Objects.equals(this.chain, servicesCustomMintBatchDto.chain) &&
        Objects.equals(this.contractAddress, servicesCustomMintBatchDto.contractAddress) &&
        Objects.equals(this.mintItems, servicesCustomMintBatchDto.mintItems);
  }

  @Override
  public int hashCode() {
    return Objects.hash(chain, contractAddress, mintItems);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServicesCustomMintBatchDto {\n");
    sb.append("    chain: ").append(toIndentedString(chain)).append("\n");
    sb.append("    contractAddress: ").append(toIndentedString(contractAddress)).append("\n");
    sb.append("    mintItems: ").append(toIndentedString(mintItems)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

