/*
 * Rainbow-API
 * The responses of the open api in swagger focus on the data field rather than the code and the message fields
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ServicesMintItemDto
 */
@JsonPropertyOrder({
  ServicesMintItemDto.JSON_PROPERTY_AMOUNT,
  ServicesMintItemDto.JSON_PROPERTY_METADATA_URI,
  ServicesMintItemDto.JSON_PROPERTY_MINT_TO_ADDRESS,
  ServicesMintItemDto.JSON_PROPERTY_TOKEN_ID
})
@JsonTypeName("services.MintItemDto")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ServicesMintItemDto {
  public static final String JSON_PROPERTY_AMOUNT = "amount";
  private Integer amount;

  public static final String JSON_PROPERTY_METADATA_URI = "metadata_uri";
  private String metadataUri;

  public static final String JSON_PROPERTY_MINT_TO_ADDRESS = "mint_to_address";
  private String mintToAddress;

  public static final String JSON_PROPERTY_TOKEN_ID = "token_id";
  private String tokenId;

  public ServicesMintItemDto() {
  }

  public ServicesMintItemDto amount(Integer amount) {
    
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAmount() {
    return amount;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAmount(Integer amount) {
    this.amount = amount;
  }


  public ServicesMintItemDto metadataUri(String metadataUri) {
    
    this.metadataUri = metadataUri;
    return this;
  }

   /**
   * Get metadataUri
   * @return metadataUri
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_METADATA_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMetadataUri() {
    return metadataUri;
  }


  @JsonProperty(JSON_PROPERTY_METADATA_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadataUri(String metadataUri) {
    this.metadataUri = metadataUri;
  }


  public ServicesMintItemDto mintToAddress(String mintToAddress) {
    
    this.mintToAddress = mintToAddress;
    return this;
  }

   /**
   * Get mintToAddress
   * @return mintToAddress
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_MINT_TO_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMintToAddress() {
    return mintToAddress;
  }


  @JsonProperty(JSON_PROPERTY_MINT_TO_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMintToAddress(String mintToAddress) {
    this.mintToAddress = mintToAddress;
  }


  public ServicesMintItemDto tokenId(String tokenId) {
    
    this.tokenId = tokenId;
    return this;
  }

   /**
   * Get tokenId
   * @return tokenId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOKEN_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTokenId() {
    return tokenId;
  }


  @JsonProperty(JSON_PROPERTY_TOKEN_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTokenId(String tokenId) {
    this.tokenId = tokenId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServicesMintItemDto servicesMintItemDto = (ServicesMintItemDto) o;
    return Objects.equals(this.amount, servicesMintItemDto.amount) &&
        Objects.equals(this.metadataUri, servicesMintItemDto.metadataUri) &&
        Objects.equals(this.mintToAddress, servicesMintItemDto.mintToAddress) &&
        Objects.equals(this.tokenId, servicesMintItemDto.tokenId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, metadataUri, mintToAddress, tokenId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServicesMintItemDto {\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    metadataUri: ").append(toIndentedString(metadataUri)).append("\n");
    sb.append("    mintToAddress: ").append(toIndentedString(mintToAddress)).append("\n");
    sb.append("    tokenId: ").append(toIndentedString(tokenId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

