/*
 * Rainbow-API
 * The responses of the open api in swagger focus on the data field rather than the code and the message fields
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ServicesSetSponsorResp
 */
@JsonPropertyOrder({
  ServicesSetSponsorResp.JSON_PROPERTY_SPONSOR_COLLATERAL_TX_ID,
  ServicesSetSponsorResp.JSON_PROPERTY_SPONSOR_GAS_TX_ID
})
@JsonTypeName("services.SetSponsorResp")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ServicesSetSponsorResp {
  public static final String JSON_PROPERTY_SPONSOR_COLLATERAL_TX_ID = "sponsor_collateral_tx_id";
  private Integer sponsorCollateralTxId;

  public static final String JSON_PROPERTY_SPONSOR_GAS_TX_ID = "sponsor_gas_tx_id";
  private Integer sponsorGasTxId;

  public ServicesSetSponsorResp() {
  }

  public ServicesSetSponsorResp sponsorCollateralTxId(Integer sponsorCollateralTxId) {
    
    this.sponsorCollateralTxId = sponsorCollateralTxId;
    return this;
  }

   /**
   * Get sponsorCollateralTxId
   * @return sponsorCollateralTxId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SPONSOR_COLLATERAL_TX_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSponsorCollateralTxId() {
    return sponsorCollateralTxId;
  }


  @JsonProperty(JSON_PROPERTY_SPONSOR_COLLATERAL_TX_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSponsorCollateralTxId(Integer sponsorCollateralTxId) {
    this.sponsorCollateralTxId = sponsorCollateralTxId;
  }


  public ServicesSetSponsorResp sponsorGasTxId(Integer sponsorGasTxId) {
    
    this.sponsorGasTxId = sponsorGasTxId;
    return this;
  }

   /**
   * Get sponsorGasTxId
   * @return sponsorGasTxId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SPONSOR_GAS_TX_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSponsorGasTxId() {
    return sponsorGasTxId;
  }


  @JsonProperty(JSON_PROPERTY_SPONSOR_GAS_TX_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSponsorGasTxId(Integer sponsorGasTxId) {
    this.sponsorGasTxId = sponsorGasTxId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServicesSetSponsorResp servicesSetSponsorResp = (ServicesSetSponsorResp) o;
    return Objects.equals(this.sponsorCollateralTxId, servicesSetSponsorResp.sponsorCollateralTxId) &&
        Objects.equals(this.sponsorGasTxId, servicesSetSponsorResp.sponsorGasTxId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sponsorCollateralTxId, sponsorGasTxId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServicesSetSponsorResp {\n");
    sb.append("    sponsorCollateralTxId: ").append(toIndentedString(sponsorCollateralTxId)).append("\n");
    sb.append("    sponsorGasTxId: ").append(toIndentedString(sponsorGasTxId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

