/*
 * Rainbow-API
 * The responses of the open api in swagger focus on the data field rather than the code and the message fields
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.client.model.MultipartFileHeader;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ServicesEasyMintFileDto
 */
@JsonPropertyOrder({
  ServicesEasyMintFileDto.JSON_PROPERTY_CHAIN,
  ServicesEasyMintFileDto.JSON_PROPERTY_DESCRIPTION,
  ServicesEasyMintFileDto.JSON_PROPERTY_FILE,
  ServicesEasyMintFileDto.JSON_PROPERTY_MINT_TO_ADDRESS,
  ServicesEasyMintFileDto.JSON_PROPERTY_NAME
})
@JsonTypeName("services.EasyMintFileDto")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ServicesEasyMintFileDto {
  public static final String JSON_PROPERTY_CHAIN = "chain";
  private String chain;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_FILE = "file";
  private MultipartFileHeader _file;

  public static final String JSON_PROPERTY_MINT_TO_ADDRESS = "mint_to_address";
  private String mintToAddress;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public ServicesEasyMintFileDto() {
  }

  public ServicesEasyMintFileDto chain(String chain) {
    
    this.chain = chain;
    return this;
  }

   /**
   * Get chain
   * @return chain
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CHAIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getChain() {
    return chain;
  }


  @JsonProperty(JSON_PROPERTY_CHAIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setChain(String chain) {
    this.chain = chain;
  }


  public ServicesEasyMintFileDto description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDescription(String description) {
    this.description = description;
  }


  public ServicesEasyMintFileDto _file(MultipartFileHeader _file) {
    
    this._file = _file;
    return this;
  }

   /**
   * Get _file
   * @return _file
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_FILE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public MultipartFileHeader getFile() {
    return _file;
  }


  @JsonProperty(JSON_PROPERTY_FILE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFile(MultipartFileHeader _file) {
    this._file = _file;
  }


  public ServicesEasyMintFileDto mintToAddress(String mintToAddress) {
    
    this.mintToAddress = mintToAddress;
    return this;
  }

   /**
   * Get mintToAddress
   * @return mintToAddress
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_MINT_TO_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMintToAddress() {
    return mintToAddress;
  }


  @JsonProperty(JSON_PROPERTY_MINT_TO_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMintToAddress(String mintToAddress) {
    this.mintToAddress = mintToAddress;
  }


  public ServicesEasyMintFileDto name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServicesEasyMintFileDto servicesEasyMintFileDto = (ServicesEasyMintFileDto) o;
    return Objects.equals(this.chain, servicesEasyMintFileDto.chain) &&
        Objects.equals(this.description, servicesEasyMintFileDto.description) &&
        Objects.equals(this._file, servicesEasyMintFileDto._file) &&
        Objects.equals(this.mintToAddress, servicesEasyMintFileDto.mintToAddress) &&
        Objects.equals(this.name, servicesEasyMintFileDto.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(chain, description, _file, mintToAddress, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServicesEasyMintFileDto {\n");
    sb.append("    chain: ").append(toIndentedString(chain)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    _file: ").append(toIndentedString(_file)).append("\n");
    sb.append("    mintToAddress: ").append(toIndentedString(mintToAddress)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

