/*
 * Rainbow-API
 * The responses of the open api in swagger focus on the data field rather than the code and the message fields
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ServicesContractAdminUpdateDto
 */
@JsonPropertyOrder({
  ServicesContractAdminUpdateDto.JSON_PROPERTY_ADMIN_ADDRESS
})
@JsonTypeName("services.ContractAdminUpdateDto")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ServicesContractAdminUpdateDto {
  public static final String JSON_PROPERTY_ADMIN_ADDRESS = "admin_address";
  private String adminAddress;

  public ServicesContractAdminUpdateDto() {
  }

  public ServicesContractAdminUpdateDto adminAddress(String adminAddress) {
    
    this.adminAddress = adminAddress;
    return this;
  }

   /**
   * Chain           string &#x60;form:\&quot;chain\&quot; json:\&quot;chain\&quot; binding:\&quot;required,oneof&#x3D;conflux conflux_test\&quot;&#x60; ContractAddress string &#x60;form:\&quot;contract_address\&quot; json:\&quot;contract_address\&quot; binding:\&quot;required\&quot;&#x60;
   * @return adminAddress
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Chain           string `form:\"chain\" json:\"chain\" binding:\"required,oneof=conflux conflux_test\"` ContractAddress string `form:\"contract_address\" json:\"contract_address\" binding:\"required\"`")
  @JsonProperty(JSON_PROPERTY_ADMIN_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAdminAddress() {
    return adminAddress;
  }


  @JsonProperty(JSON_PROPERTY_ADMIN_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAdminAddress(String adminAddress) {
    this.adminAddress = adminAddress;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServicesContractAdminUpdateDto servicesContractAdminUpdateDto = (ServicesContractAdminUpdateDto) o;
    return Objects.equals(this.adminAddress, servicesContractAdminUpdateDto.adminAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adminAddress);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServicesContractAdminUpdateDto {\n");
    sb.append("    adminAddress: ").append(toIndentedString(adminAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

