/*
 * Rainbow-API
 * The responses of the open api in swagger focus on the data field rather than the code and the message fields
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import java.io.File;
import org.openapitools.client.model.ModelsFilesQueryResult;
import org.openapitools.client.model.RainbowErrorsRainbowErrorDetailInfo;
import org.openapitools.client.model.ServicesUploadFilesResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for FilesApi
 */
@Ignore
public class FilesApiTest {

    private final FilesApi api = new FilesApi();

    
    /**
     * Obtain file list
     *
     * Get the file list containing the info of the files uploaded in the specified app
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listFilesTest() throws ApiException {
        String authorization = null;
        String page = null;
        String limit = null;
        ModelsFilesQueryResult response = 
        api.listFiles(authorization, page, limit);
        
        // TODO: test validations
    }
    
    /**
     * Upload file
     *
     * Upload a file which can be a video, an image and so on
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void uploadFileTest() throws ApiException {
        String authorization = null;
        File _file = null;
        ServicesUploadFilesResponse response = 
        api.uploadFile(authorization, _file);
        
        // TODO: test validations
    }
    
    /**
     * Upload file to OSS
     *
     * Upload a file to OSS, which can be a video, an image and so on
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void uploadFileToOssTest() throws ApiException {
        String authorization = null;
        File _file = null;
        ServicesUploadFilesResponse response = 
        api.uploadFileToOss(authorization, _file);
        
        // TODO: test validations
    }
    
}
