/*
 * Rainbow-API
 * The responses of the open api in swagger focus on the data field rather than the code and the message fields
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.MiddlewaresAppLogin;
import org.openapitools.client.model.MiddlewaresLoginResp;
import org.openapitools.client.model.RainbowErrorsRainbowErrorDetailInfo;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for LoginApi
 */
@Ignore
public class LoginApiTest {

    private final LoginApi api = new LoginApi();

    
    /**
     * App login
     *
     * Login the app to get the JWT according to the app_id and app_secret
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void loginAppTest() throws ApiException {
        MiddlewaresAppLogin appLoginInfo = null;
        MiddlewaresLoginResp response = 
        api.loginApp(appLoginInfo);
        
        // TODO: test validations
    }
    
    /**
     * Refresh JWT
     *
     * Obtain a new JWT
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void refreshAuthTest() throws ApiException {
        String authorization = null;
        MiddlewaresLoginResp response = 
        api.refreshAuth(authorization);
        
        // TODO: test validations
    }
    
}
