/*
 * Rainbow-API
 * The responses of the open api in swagger focus on the data field rather than the code and the message fields
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.RainbowErrorsRainbowErrorDetailInfo;
import org.openapitools.client.model.ServicesNFT;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for NftsApi
 */
@Ignore
public class NftsApiTest {

    private final NftsApi api = new NftsApi();

    
    /**
     * Get NFT info, mainly owner and metadata
     *
     * Get NFT info, mainly owner and metadata
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void nFTInfoTest() throws ApiException {
        String authorization = null;
        String address = null;
        String tokenId = null;
        ServicesNFT response = 
        api.nFTInfo(authorization, address, tokenId);
        
        // TODO: test validations
    }
    
}
